package com.skyfix.persistence;

/**
 * A stored telemetry log. Row shape of {@code flight_log}.
 *
 * @param id          database key, or {@code null} before insertion
 * @param missionId   owning mission
 * @param name        log name, unique within the mission
 * @param sourceKind  {@code RECORDED} or {@code SYNTHETIC}, matching the schema's CHECK
 * @param fileSha256  SHA-256 of the source file
 * @param sampleCount how many samples the log holds
 * @param truthJson   for a synthetic flight, what it really did — the answer T-V5 and T-V6 are
 *                    scored against; {@code null} for a recorded flight, where nobody knows
 */
public record FlightLog(Long id, long missionId, String name, String sourceKind,
                        String fileSha256, int sampleCount, String truthJson) {

    /** Source kind for a log recorded from real hardware. */
    public static final String RECORDED = "RECORDED";
    /** Source kind for a log generated by {@code SyntheticFlightWriter}. */
    public static final String SYNTHETIC = "SYNTHETIC";

    /**
     * @param newId the assigned key
     * @return the identified log
     */
    public FlightLog withId(long newId) {
        return new FlightLog(newId, missionId, name, sourceKind, fileSha256, sampleCount,
                truthJson);
    }

    /** @return whether this log carries known truth, and so can be scored against */
    public boolean hasTruth() {
        return truthJson != null && !truthJson.isBlank();
    }
}
