package com.skyfix.io;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.skyfix.core.atmos.AtmosphereModel;
import com.skyfix.core.atmos.AtmosphericState;
import com.skyfix.core.atmos.WindField;
import com.skyfix.core.flight.FlightSimulator;
import com.skyfix.domain.BalloonConfig;
import com.skyfix.domain.BalloonState;
import com.skyfix.domain.FlightParameters;
import com.skyfix.domain.FlightTruth;
import com.skyfix.domain.Gaussian;
import com.skyfix.domain.GeoPoint;
import com.skyfix.domain.Geodesy;
import com.skyfix.domain.NoiseSpec;
import com.skyfix.domain.SimSettings;
import com.skyfix.domain.StateHistory;
import com.skyfix.domain.error.PersistenceException;
import com.skyfix.domain.error.SkyfixException;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Locale;
import java.util.SplittableRandom;

/**
 * Generates a synthetic flight with known truth and writes it as a telemetry log (FR-1.4, DS-6).
 *
 * <p>No real 30 km or 45 km flight log exists yet, so this is the evaluation set O3 and O4 are
 * scored on. Each flight forward-simulates from truth parameters, then corrupts the result the way
 * a flight computer does — GPS noise, barometer noise, and dropouts that come in runs rather than
 * as isolated samples — and writes what the radio would have delivered, not what the simulator
 * knew.
 *
 * <p><strong>Byte-identical regeneration.</strong> FR-1.4 requires that the same seed reproduces
 * the same file exactly. Three things make that hold: all noise comes from a
 * {@link SplittableRandom} seeded from the flight seed alone; every number is formatted with
 * {@link Locale#ROOT}, so a machine with a comma decimal separator writes the same bytes; and the
 * line separator is written explicitly rather than taken from the platform.
 */
public final class SyntheticFlightWriter {

    /** Telemetry cadence, seconds. A 1 Hz log is what the HabSat flight computer produces. */
    public static final double SAMPLE_INTERVAL_S = 1.0;

    private static final String NEWLINE = "\n";

    private final AtmosphereModel atmosphere;
    private final WindField windField;

    /**
     * @param atmosphere the atmosphere the flight is simulated in
     * @param windField  the wind the flight is advected by
     */
    public SyntheticFlightWriter(AtmosphereModel atmosphere, WindField windField) {
        this.atmosphere = atmosphere;
        this.windField = windField;
    }

    /**
     * Generates one flight and writes its telemetry log.
     *
     * @param path        the CSV file to write
     * @param config      the balloon configuration
     * @param truthParams the true flight parameters this flight actually flew
     * @param settings    integration settings
     * @param launch      the launch position
     * @param launchEpoch the launch time
     * @param noise       how the telemetry is corrupted
     * @param seed        the flight seed; the same seed reproduces the file byte for byte
     * @return what the flight really did, for scoring
     * @throws SkyfixException if the flight cannot be simulated or the file cannot be written
     */
    public FlightTruth write(Path path, BalloonConfig config, FlightParameters truthParams,
                             SimSettings settings, GeoPoint launch, Instant launchEpoch,
                             NoiseSpec noise, long seed) throws SkyfixException {

        // Every retained state becomes a packet, so the stride is set to match the cadence rather
        // than left at whatever the caller happened to use for a prediction.
        int stride = Math.max(1, (int) Math.round(SAMPLE_INTERVAL_S / settings.stepSeconds()));
        SimSettings sampling = settings.toBuilder().stateSampleStride(stride).build();

        StateHistory history = new FlightSimulator(atmosphere, windField)
                .run(config, truthParams, sampling, launch);
        BalloonState landing = history.landing().orElseThrow(() ->
                new com.skyfix.domain.error.ConvergenceException(
                        "synthetic flight with seed " + seed + " never reached the ground"));

        SplittableRandom random = new SplittableRandom(seed);
        int dropoutRemaining = 0;
        int written = 0;

        try {
            Files.createDirectories(path.toAbsolutePath().getParent());
            try (BufferedWriter out = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
                out.write("# SYNTHETIC telemetry generated by SKYFIX (FR-1.4, DS-6). "
                        + "Not an observation.");
                out.write(NEWLINE);
                out.write("# seed=" + seed + "  regenerate with: run.sh synth --seed " + seed);
                out.write(NEWLINE);
                out.write("epoch_utc,packet_id,lat,lon,alt_gps_m,pressure_pa,temperature_k");
                out.write(NEWLINE);

                int packetId = 0;
                for (BalloonState state : history) {
                    Instant epoch = launchEpoch.plusMillis(
                            Math.round(state.timeSeconds() * 1000.0));

                    // A dropout, once begun, runs for several packets: a GPS receiver that loses
                    // lock does not recover on the very next sample, and an estimator that only
                    // ever saw isolated single-sample gaps would be tuned for a fiction.
                    if (dropoutRemaining == 0
                            && random.nextDouble() < noise.dropoutProbability()) {
                        dropoutRemaining = noise.dropoutRunLength();
                    }
                    boolean dropped = dropoutRemaining > 0;
                    if (dropped) {
                        dropoutRemaining--;
                    }

                    AtmosphericState air = atmosphere.stateAt(state.altitudeM());
                    double latNoiseM = noise.gpsHorizontalSigmaM() * gauss(random);
                    double lonNoiseM = noise.gpsHorizontalSigmaM() * gauss(random);
                    double altNoise = noise.gpsAltitudeSigmaM() * gauss(random);
                    double pressure = air.pressurePa()
                            * (1.0 + noise.pressureRelativeSigma() * gauss(random));
                    double temperature = air.temperatureK()
                            + noise.temperatureSigmaK() * gauss(random);

                    double lat = state.latitudeDeg()
                            + latNoiseM / Geodesy.metresPerDegreeLatitude();
                    double lon = state.longitudeDeg() + lonNoiseM
                            / Geodesy.metresPerDegreeLongitude(state.latitudeDeg());

                    out.write(String.format(Locale.ROOT, "%s,%d,%.6f,%.6f,%s,%.1f,%.2f",
                            epoch, packetId, lat, Geodesy.normaliseLongitude(lon),
                            dropped ? "" : String.format(Locale.ROOT, "%.1f",
                                    state.altitudeM() + altNoise),
                            pressure, temperature));
                    out.write(NEWLINE);
                    packetId++;
                    written++;
                }
            }
        } catch (IOException e) {
            throw new PersistenceException("cannot write synthetic telemetry to " + path, e);
        }

        return new FlightTruth(seed, truthParams,
                history.burstAltitudeM().orElse(Double.NaN),
                history.burst().map(b -> launchEpoch
                        .plusMillis(Math.round(b.timeSeconds() * 1000.0)).toString()).orElse(null),
                landing.latitudeDeg(), landing.longitudeDeg(),
                launchEpoch.plusMillis(Math.round(landing.timeSeconds() * 1000.0)).toString(),
                written);
    }

    /**
     * Renders a flight's truth as JSON, for the {@code flight_log.truth_json} column.
     *
     * @param truth the truth to render
     * @return a compact JSON object
     * @throws PersistenceException if the JSON cannot be produced
     */
    public static String truthJson(FlightTruth truth) throws PersistenceException {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode node = mapper.createObjectNode();
        node.put("seed", truth.seed());
        node.put("free_lift_kg", truth.parameters().freeLiftKg());
        node.put("ascent_cd", truth.parameters().ascentCd());
        node.put("burst_diameter_m", truth.parameters().burstDiameterM());
        node.put("chute_cd", truth.parameters().chuteCd());
        node.put("wind_scale", truth.parameters().windScale());
        node.put("burst_alt_m", truth.burstAltitudeM());
        node.put("burst_epoch_utc", truth.burstEpochUtc());
        node.put("landing_lat", truth.landingLatDeg());
        node.put("landing_lon", truth.landingLonDeg());
        node.put("landing_epoch_utc", truth.landingEpochUtc());
        node.put("sample_count", truth.sampleCount());
        try {
            return mapper.writeValueAsString(node);
        } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
            throw new PersistenceException("cannot render flight truth as JSON", e);
        }
    }

    /**
     * A standard normal draw, by the Box-Muller transform.
     *
     * <p>Hand-written like the rest of the maths (CLAUDE.md rule 1), and built on
     * {@link Gaussian#inverseCdf} rather than a second implementation, so there is one definition
     * of "normal" in the codebase and the tests that pin it cover this path too.
     */
    private static double gauss(SplittableRandom random) {
        // nextDouble() is in [0, 1); the inverse CDF needs the open interval.
        double u = Math.min(1.0 - 1e-15, Math.max(1e-15, random.nextDouble()));
        return Gaussian.inverseCdf(u);
    }
}
